### ISSUE TITLE
Do I need a local node? HowTo remote node?

### ISSUE THREAD

**Issue by Jzarecta** [sebicas/bitcoin-sniffer#2]
Hi I wonder if I can have a remote node and how can I get the connection working. Thinking that I will probably be on a small VPS with limited storage, I wonder how can I code to a remote blockchain at least to find events and transactions.

**Comment by sgornick** [comment]
You can RPC to a Bitcoin Core node from a remote host.    Btcoin-sniffer was useful before there was WalletNotify and BlockNotify commands. 

https://bitcointalk.org/index.php?topic=1442574.0

As far as allowing connections from your remote client, see RPC connnection parameters: https://en.bitcoin.it/wiki/Running_Bitcoin#Command-line_arguments   (e.g., rpcuser, rpcpassword, rpcallowip ).

Also, you can use ZMQ https://github.com/bitcoin/bitcoin/blob/master/doc/zmq.md

**Comment by sebicas** [comment]
Both options will work... if you don't like to relay on a 3rd party run your own local node.
