### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by benzmuircroft** [sebicas/bitcoin-sniffer#3]
Bitcoin Network Sniffer v0.0.2

---

 Connecting to Bitcoin Node IP # 173.242.112.53:8333
error: uncaptured python exception, closing channel <**main**.NodeConn 173.242.112.53:8333 at 0xd5e878> (<class 'socket.error'>:[Errno 110] Connection timed out [/usr/lib64/python2.7/asyncore.py|read|83] [/usr/lib64/python2.7/asyncore.py|handle_read_event|446] [/usr/lib64/python2.7/asyncore.py|handle_connect_event|454])
 Closing Conection ... bye :)

Do I need to change something in my firewall for this to work?

I just uploaded sniffer.py to my server
chmod 755 the script then run it...

**Comment by sebicas** [comment]
Check that Port 8333 is open on IP 173.242.112.53

**Comment by benzmuircroft** [comment]
I opened the port and chose a node ip from https://blockchain.info/ip-log

and It works

You are so amazingly freeking cool dude! be very proud!

_Takes hat off..._
