### ISSUE TITLE
How to tell if the block will be part of the main chain?

### ISSUE THREAD

**Issue by benzmuircroft** [sebicas/bitcoin-sniffer#6]
After finding that the block comes with no 'block height' I found this question: http://bitcoin.stackexchange.com/questions/24309/is-block-height-always-sequential

> Block height is by definition sequential in the sense that adjacent blocks will always have heights that differ by 1. But there is a chicken-and-egg problem: in order to compute the height, you have to have access to all the blocks in between the genesis block and the current one. (The height is not recorded in the block itself.)
> There's also the issue that multiple blocks can have the same height, if they are on different branches of the chain. So just because you have one block at every height, doesn't mean you have all the blocks on the main chain; some of them might be on orphan branches.

**what is block.is_valid? and how can i tell if the block is official and will not be replaced by a _'better'_ block?**

**Comment by benzmuircroft** [comment]
I've opened up the question publicly to get more advice:

http://bitcoin.stackexchange.com/questions/48740/how-can-i-trust-a-new-block-broadcated-on-the-network

**Comment by sebicas** [comment]
You need to trace it down to the genesis block, that is the only way.

With this software, we don't do block validation, we blindly relay on the full node we connect to.
