### ISSUE TITLE
tx.vout (where is) asm and hex

### ISSUE THREAD

**Issue by benzmuircroft** [sebicas/bitcoin-sniffer#9]
in each `tx.vout` is there a `asm` and `hex`?

shouldn't the `scriptPubKey` contain 
```

   "asm": "OP_DUP OP_HASH160 2544bedede7298fe7cedb3fcd0eb5fa73729eb64 OP_EQUALVERIFY OP_CHECKSIG",
   "hex": "76a9142544bedede7298fe7cedb3fcd0eb5fa73729eb6488ac",
   "reqSigs": 1,
   "type": "pubkeyhash",
   "addresses": [
                    "14Q4MdFGqFbP9WPzz3AXjsdxZC68rCQjj1"
                    ]
                
```

Insead I see 

```
v��_/{�/k>//��7`HH��
```

**Comment by sebicas** [comment]
Honestly I don't remember, long time ago don't use this code.

I guess is base58 encoded.

Check http://bitcoin.stackexchange.com/questions/36634/how-do-i-get-to-the-value-in-the-scriptpubkey-part-of-the-transaction

**Comment by benzmuircroft** [comment]
```
def new_transaction_event(tx):
	print str(tx)
```

shows scriptPubKey completly differently

`CTransaction(nVersion=1 vin=[CTxIn(prevout=COutPoint(hash=a8d876a3883d9f2f104ddada0aa2839ca31a4ba636b3a1601b908008f58fbb21 n=17) scriptSig=47304402201c3fb1f3a15d33b14d8e6ba2aba9970e7d7eb3f4769efc2243133230b6e8c5310220528d6ba75c628919104017b96bde7cace085b839b9acd4017720b77c0cd35f4a012102bc3635a170a77714dc03b0bd74a5fb9923a3666764ac066f6f3514c205eafdef nSequence=4294967295)] vout=[CTxOut(nValue=0.00006559 scriptPubKey=76a9146ebffbba9dc304de9df3e2d7a03ed9f88bbe58bd88ac), CTxOut(nValue=0.00416667 scriptPubKey=a914977052847eee991bffdb32a3dcd92983d68f46e687)] nLockTime=0)
`
